development:
  email_from: "frames@framefox.com.au"
  api_url: "http://dev.framefox.com.au:3001"
  api_base_path: "/api"
  shopify_domain: "<%= ENV['remote_shopify_domain_au'] %>"
  shopify_access_token: "<%= ENV['remote_shopify_access_token_au'] %>"
  currency: "AUD"
  country_code: "AU"
  country_name: "Australia"
  shopify_remote_store: "https://admin.shopify.com/store/framefox-au-prod/"

production:
  email_from: "frames@framefox.com.au"
  api_url: "https://shop.framefox.com.au"
  api_base_path: "/api"
  shopify_domain: "<%= ENV['remote_shopify_domain_au'] %>"
  shopify_access_token: "<%= ENV['remote_shopify_access_token_au'] %>"
  currency: "AUD"
  country_code: "AU"
  country_name: "Australia"
  shopify_remote_store: "https://admin.shopify.com/store/framefox-au-prod/"
